"""initial schema

Revision ID: 6778c73c56c7
Revises: 
Create Date: 2026-04-12 00:38:39.276075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6778c73c56c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'chair', 'vice_chair', 'secretary', 'treasurer', 'member', name='role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_voting_member', sa.Boolean(), nullable=False),
    sa.Column('committees', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('meeting_type', sa.Enum('regular', 'special', 'annual', 'emergency', name='meetingtype', native_enum=False), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'adjourned', 'cancelled', name='meetingstatus', native_enum=False), nullable=False),
    sa.Column('current_stage', sa.Enum('not_started', 'call_to_order', 'roll_call', 'minutes_approval', 'reports', 'unfinished_business', 'new_business', 'announcements', 'adjourned', name='meetingstage', native_enum=False), nullable=False),
    sa.Column('current_agenda_item_id', sa.Integer(), nullable=True),
    sa.Column('current_motion_id', sa.Integer(), nullable=True),
    sa.Column('called_to_order_at', sa.DateTime(), nullable=True),
    sa.Column('adjourned_at', sa.DateTime(), nullable=True),
    sa.Column('minutes_approved_at', sa.DateTime(), nullable=True),
    sa.Column('minutes_approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_agenda_item_id'], ['agenda_items.id'], name='fk_meeting_current_agenda', use_alter=True),
    sa.ForeignKeyConstraint(['current_motion_id'], ['motions.id'], name='fk_meeting_current_motion', use_alter=True),
    sa.ForeignKeyConstraint(['minutes_approved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agenda_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('call_to_order', 'roll_call', 'minutes_approval', 'report', 'unfinished_business', 'new_business', 'announcement', 'adjournment', name='agendacategory', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('presenter_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'skipped', name='agendaitemstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['presenter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rsvp_status', sa.Enum('yes', 'no', 'maybe', 'no_response', name='rsvpstatus', native_enum=False), nullable=False),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.Column('departed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uq_attendance_meeting_user')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.Enum('treasurer', 'committee', 'pastor', 'other', name='reporttype', native_enum=False), nullable=False),
    sa.Column('committee', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('submitted_by_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('agenda_item_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(CASE WHEN meeting_id IS NULL THEN 0 ELSE 1 END + CASE WHEN agenda_item_id IS NULL THEN 0 ELSE 1 END + CASE WHEN report_id IS NULL THEN 0 ELSE 1 END) = 1', name='ck_attachment_single_parent'),
    sa.ForeignKeyConstraint(['agenda_item_id'], ['agenda_items.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_table('motions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('agenda_item_id', sa.Integer(), nullable=True),
    sa.Column('parent_motion_id', sa.Integer(), nullable=True),
    sa.Column('motion_type', sa.Enum('main', 'amendment', 'substitute_amendment', 'table', 'postpone', 'call_question', 'adjourn', 'recess', 'point_of_order', name='motiontype', native_enum=False), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('maker_id', sa.Integer(), nullable=False),
    sa.Column('seconder_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('proposed', 'seconded', 'debating', 'voting', 'passed', 'failed', 'withdrawn', 'tabled', name='motionstatus', native_enum=False), nullable=False),
    sa.Column('yes_count', sa.Integer(), nullable=False),
    sa.Column('no_count', sa.Integer(), nullable=False),
    sa.Column('abstain_count', sa.Integer(), nullable=False),
    sa.Column('result', sa.Enum('passed', 'failed', name='motionresult', native_enum=False), nullable=True),
    sa.Column('requires_majority', sa.Enum('simple', 'two_thirds', name='majorityrule', native_enum=False), nullable=False),
    sa.Column('vote_method', sa.Enum('voice', 'roll_call', name='votemethod', native_enum=False), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agenda_item_id'], ['agenda_items.id'], ),
    sa.ForeignKeyConstraint(['maker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['parent_motion_id'], ['motions.id'], ),
    sa.ForeignKeyConstraint(['seconder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('minutes_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('entry_type', sa.Enum('stage_change', 'attendance', 'agenda_item', 'motion_made', 'motion_seconded', 'motion_amended', 'motion_voted', 'motion_withdrawn', 'report_presented', 'announcement', 'chair_note', 'adjournment', name='minutesentrytype', native_enum=False), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('related_motion_id', sa.Integer(), nullable=True),
    sa.Column('related_agenda_item_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['related_agenda_item_id'], ['agenda_items.id'], ),
    sa.ForeignKeyConstraint(['related_motion_id'], ['motions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motion_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('choice', sa.Enum('yes', 'no', 'abstain', name='votechoice', native_enum=False), nullable=False),
    sa.Column('cast_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['motion_id'], ['motions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('motion_id', 'user_id', name='uq_vote_motion_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('minutes_entries')
    op.drop_table('motions')
    op.drop_table('attachments')
    op.drop_table('reports')
    op.drop_table('meeting_attendances')
    op.drop_table('agenda_items')
    op.drop_table('meetings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
